"""Patch the source registry and data dictionary for the 8-30 day extended outlook.

Why this is a separate script instead of an edit to gen_docs.py: gen_docs.py reads
/home/user/workspace/socal/data/out, which no longer exists in this checkout, so it cannot be
re-run. This script is additive and idempotent -- it rewrites only the extended-range blocks,
delimited by HTML comment markers, and leaves every pre-existing section untouched.

Writes:
  pipeline/config/sources.json          new registry entries + new gap notes
  dataset/csv/source_registry.csv       same registry, flat
  docs/SOURCE_REGISTRY.md               new "Extended-range (8-30 day) sources" section
  docs/DATA_DICTIONARY.md               new extended_outlook / extended_scores field tables
  README.md                             short pointer to the extended tab

Run:  python pipeline/gen_extended_docs.py
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV_DIR = os.path.join(ROOT, "dataset", "csv")
DOCS = os.path.join(ROOT, "docs")
CFG = os.path.join(HERE, "config", "sources.json")

BEG = "<!-- BEGIN extended-range (generated by pipeline/gen_extended_docs.py) -->"
END = "<!-- END extended-range -->"

# --------------------------------------------------------------------------- registry additions
# NOTE ON BASIS: every field in the extended tables is tagged forecast / blend / climatology /
# enso_analog / astronomical / metadata in dataset/csv/extended_field_provenance.csv, which is the
# machine-readable answer to "is this a real forecast or a historical pattern estimate?".
NEW_SOURCES = [
    {
        "id": "cpc_814_outlook",
        "name": "CPC 8-14 day temperature and precipitation outlook (GIS shapefiles)",
        "provider": "NOAA Climate Prediction Center",
        "url": "https://www.cpc.ncep.noaa.gov/products/predictions/814day/",
        "endpoint": "https://ftp.cpc.ncep.noaa.gov/GIS/us_tempprcpfcst/814temp_latest.zip",
        "stations": "Sampled at the San Diego onshore proxy point -117.15, 32.70",
        "used_for": "Probabilistic warm/cool lean applied as an additive nudge to the day 7-14 SST "
                    "projection (cpc_nudge_f), and the CPC columns shown on the 30-Day Outlook tab",
        "coverage": "Days 8-14 from the issuance date",
        "cadence": "Daily",
        "access": "Public, no key",
        "units": "Tercile probability in percent, converted to a signed degF nudge",
        "license": "US Government work, public domain",
        "limitations": "BASIS = forecast, but a LAND forecast: this is a CONUS *air* temperature tercile "
                       "product, not a marine SST forecast. No polygon covers the offshore zones, so a "
                       "single onshore San Diego proxy point is sampled for all nine zones including "
                       "Cortez Bank at 95 nm. The true coastal point -117.22, 32.72 falls outside every "
                       "CPC CONUS polygon. Equal-Chances areas contribute exactly zero signal.",
    },
    {
        "id": "cpc_wk34_outlook",
        "name": "CPC week 3-4 temperature and precipitation outlook (GIS shapefiles)",
        "provider": "NOAA Climate Prediction Center",
        "url": "https://www.cpc.ncep.noaa.gov/products/predictions/WK34/",
        "endpoint": "https://ftp.cpc.ncep.noaa.gov/GIS/us_tempprcpfcst/wk34temp_latest.zip",
        "stations": "Sampled at the San Diego onshore proxy point -117.15, 32.70",
        "used_for": "Probabilistic warm/cool lean for the day 15-28 outlook tier",
        "coverage": "Weeks 3 and 4 from the issuance date",
        "cadence": "Weekly (Friday)",
        "access": "Public, no key",
        "units": "Tercile probability in percent",
        "license": "US Government work, public domain",
        "limitations": "BASIS = forecast. Same land/CONUS air-temperature caveat as the 8-14 day product, "
                       "and it is a two-week average, so it carries no day-to-day information at all. "
                       "Down-weighted to 0.32 in the extended blend.",
    },
    {
        "id": "cpc_monthly_seasonal_outlook",
        "name": "CPC monthly and seasonal temperature outlooks (GIS shapefiles)",
        "provider": "NOAA Climate Prediction Center",
        "url": "https://www.cpc.ncep.noaa.gov/products/predictions/long_range/",
        "endpoint": "https://ftp.cpc.ncep.noaa.gov/GIS/us_tempprcpfcst/seastemp_{YYYYMM}.zip",
        "stations": "Sampled at the San Diego onshore proxy point -117.15, 32.70",
        "used_for": "Weakest-weighted warm/cool lean at the far end of the 30-day window",
        "coverage": "Monthly lead 1 and seasonal leads",
        "cadence": "Monthly (mid-month), with a monthly update near the end of the month",
        "access": "Public, no key",
        "units": "Tercile probability in percent",
        "license": "US Government work, public domain",
        "limitations": "BASIS = forecast, weakly weighted (0.20 monthly, 0.15 seasonal). At this build the "
                       "monthly *update* product was stale, so the September outlook was read from the "
                       "seasonal lead-14 file instead, and at 33 percent probability it is Equal Chances "
                       "and contributes exactly zero signal. Same land/CONUS air-temperature caveat.",
    },
    {
        "id": "coops_predictions_extended",
        "name": "CO-OPS tide predictions, extended horizon",
        "provider": "NOAA Tides & Currents",
        "url": "https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=9410170",
        "endpoint": "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions"
                    "&station={station}&begin_date={YYYYMMDD}&end_date={YYYYMMDD}&datum=MLLW"
                    "&interval=hilo&units=english&time_zone=lst_ldt&format=json",
        "stations": "9410170 San Diego Bay (Broadway Pier), 9410230 La Jolla (Scripps Pier)",
        "used_for": "Tide range, strongest exchange rate and best-water hour for all 30 days",
        "coverage": "Verified working at least 40 days ahead",
        "cadence": "Static harmonic predictions",
        "access": "Public, no key",
        "units": "ft MLLW, ft/h, local hour",
        "license": "US Government work, public domain",
        "limitations": "BASIS = astronomical, so these are exactly as reliable at day 30 as at day 1 and are "
                       "the strongest signal in the outlook tier. Harmonic predictions exclude weather-driven "
                       "surge and river/runoff effects. On strongly diurnal days the daily extremum window is "
                       "narrowed to the day's single extremum plus the closer of its two neighbours, flagged "
                       "by tide_window_widened, to avoid inflating the range across two exchanges.",
    },
    {
        "id": "openmeteo_16day",
        "name": "Open-Meteo 16-day marine and atmospheric forecast",
        "provider": "Open-Meteo",
        "url": "https://open-meteo.com/en/docs/marine-weather-api",
        "endpoint": "https://marine-api.open-meteo.com/v1/marine?forecast_days=16 and "
                    "https://api.open-meteo.com/v1/forecast?forecast_days=16",
        "stations": "One sampling point per zone (nine zones)",
        "used_for": "The deterministic tail of the day 8-14 tier: wind, swell and pressure blended toward "
                    "climatology with weight exp(-(lead-6)/7)",
        "coverage": "16 requested days, but the two models do NOT reach equally far",
        "cadence": "Multiple runs daily",
        "access": "Public, no key",
        "units": "m, s, m/s, hPa (converted to ft, kt, degF)",
        "license": "CC-BY 4.0, non-commercial free tier",
        "limitations": "BASIS = forecast, but with a hard and unequal horizon. At this build the MARINE "
                       "(swell) fields null out after 2026-09-05, roughly lead 8, while the ATMOSPHERIC "
                       "(wind) fields run to 2026-09-12, lead 15. The two are therefore handled "
                       "independently and tagged per row by wave_basis and wind_basis. Beyond the "
                       "atmospheric horizon no daily wind or swell number is published at all.",
    },
]

NEW_GAPS = [
    "Extended range, days 15-30: no true extended MARINE forecast exists at public-API level, so "
    "wave_proj_ft, wind_proj_kt and fishability_outlook are deliberately NULL for the whole tier "
    "rather than filled with a seasonal average dressed up as a forecast.",
    "Extended range: the CPC 8-14 day, week 3-4 and monthly outlooks are CONUS land air-temperature "
    "tercile products. No polygon covers the offshore zones, so one onshore San Diego proxy point "
    "(-117.15, 32.70) is sampled for all nine zones. Treat it as a regional warm/cool lean only.",
    "Extended range: observed analog-year SST anomalies can only be computed for analog years inside "
    "the MUR satellite record, so of the eight ENSO analog years only 2023 has an observed local "
    "anomaly (and it ran counter to the composite). The primary ENSO signal is the zone composite.",
    "Extended range: barometric pressure exists only inside the deterministic model horizon. Feeding "
    "it into days 8-14 and dropping it at day 15 renormalized the driver weights and produced a false "
    "score cliff at the tier boundary, so pressure is excluded from the extended score at BOTH tiers "
    "and published only as the reference field pressure_trend_model_24h.",
    "Extended range: front strength and chlorophyll are unavailable beyond the near term, so those "
    "drivers are dropped and the remaining weights renormalize. Extended scores are directionally "
    "comparable to near-term scores but are not identically constructed.",
    "Extended range: only NDBC 46086 carries a wind climatology, so seven of nine zones fall back to "
    "it as a regional wind normal, flagged by wind_norm_is_regional_fallback. Wave climatology gets "
    "NO such fallback -- San Diego Bay and Mission Bay keep a null wave normal and honestly drop the "
    "swell driver, because substituting an offshore buoy put 8 ft swell inside a harbour.",
    "Extended range: the published score band is ratcheted so its half-width never narrows as lead "
    "time grows. The raw SST-sensitivity band can narrow at long lead where the score saturates near "
    "its soft ceiling, which would falsely imply rising certainty. Rows where the band edge is clipped "
    "by the bounded 0-100 scale are flagged by score_band_hits_ceiling / score_band_hits_floor.",
]

# --------------------------------------------------------------------------- dictionary additions
EXT_FIELDS = [
    ("date", "date", "local date", "Calendar date, America/Los_Angeles."),
    ("zone_id", "string", "—", "Fishing zone; joins to dim_zones."),
    ("lead_days", "int", "days", "Days ahead of the build date. 7-30 in this table."),
    ("confidence_tier", "int", "1-3", "1 = days 1-7 (near-term model, not in this table), 2 = days 8-14, 3 = days 15-30."),
    ("confidence_key", "string", "—", "high / moderate / outlook."),
    ("sst_norm_f", "float", "°F", "CLIMATOLOGY. Day-of-year mean SST, ±7-day window. Not a forecast."),
    ("sst_sd_f", "float", "°F", "CLIMATOLOGY. Interannual SD of that day-of-year sample; sets the band width."),
    ("sst_proj_f", "float", "°F", "BLEND. Projected SST: current anomaly persisted with weight w_persistence, "
                                  "the ENSO analog expectation with weight w_enso_analog, plus the CPC nudge."),
    ("sst_proj_lo_f", "float", "°F", "BLEND. Low edge of the projection, sst_proj_f - sst_sd_f * (0.55 + 0.038*(lead-6))."),
    ("sst_proj_hi_f", "float", "°F", "BLEND. High edge. The band widens monotonically with lead time."),
    ("sst_anom_proj_f", "float", "°F", "BLEND. sst_proj_f minus sst_norm_f."),
    ("sst_anom_core_f", "float", "°F", "BLEND. The anomaly before the CPC nudge is applied."),
    ("sst_basis", "string", "—", "Plain-language description of how this row's SST was derived."),
    ("w_persistence", "float", "0-1", "exp(-(lead-6)/8). Weight on persisting the currently observed anomaly."),
    ("w_enso_analog", "float", "0-1", "1 - w_persistence. Rises with lead, so the ENSO analog dominates far out."),
    ("w_cpc_outlook", "float", "0-1", "Weight of the CPC nudge, NOT a third share: 0.55 for days 7-14, "
                                      "0.32 week 3-4, 0.20 monthly, 0.15 seasonal. Applied additively so the "
                                      "persistence/analog split stays monotonic across tier boundaries."),
    ("cpc_nudge_f", "float", "°F", "FORECAST. w_cpc_outlook * signed CPC tercile signal. Exactly 0 for Equal Chances."),
    ("wave_norm_ft", "float", "ft", "CLIMATOLOGY. Day-of-year mean significant wave height from the zone's NDBC buoy. "
                                    "NULL for San Diego Bay and Mission Bay, which have no wave buoy and no fallback."),
    ("wind_norm_kt", "float", "kt", "CLIMATOLOGY. Day-of-year mean wind. Only NDBC 46086 has a wind climatology, so "
                                    "seven zones use it as a regional fallback."),
    ("wind_norm_is_regional_fallback", "bool", "—", "True where wind_norm_kt came from 46086 rather than the zone's own buoy."),
    ("wave_proj_ft", "float", "ft", "FORECAST/BLEND for days 7-8, then NULL. The marine model horizon is shorter "
                                    "than the atmospheric one, so swell stops earlier than wind."),
    ("wind_proj_kt", "float", "kt", "FORECAST/BLEND inside the atmospheric model horizon, then NULL. Never published "
                                    "for days 15-30."),
    ("wave_basis", "string", "—", "Per-row reason a wave value is a blend, climatology-only, or absent."),
    ("wind_basis", "string", "—", "Per-row equivalent for wind."),
    ("sea_state_published", "bool", "—", "False for the whole days 15-30 tier: no daily sea state is published."),
    ("pressure_trend_model_24h", "float", "hPa/24h", "REFERENCE ONLY. Present inside the model horizon but "
                                                     "deliberately excluded from the extended score at both tiers."),
    ("tide_range_ft", "float", "ft", "ASTRONOMICAL, exact at any lead. Range of the day's dominant exchange."),
    ("tide_window_widened", "bool", "—", "True where the day is strongly diurnal and the window was narrowed to the "
                                         "day's extremum plus its closer neighbour to avoid inflating the range."),
    ("max_exchange_rate_ft_h", "float", "ft/h", "ASTRONOMICAL. Steepest tidal exchange rate of the day."),
    ("best_water_hour", "float", "local hour", "ASTRONOMICAL. Hour of the strongest exchange, weighted toward "
                                               "dawn/dusk overlap."),
    ("moon_illum", "float", "0-1", "ASTRONOMICAL. Fraction illuminated. Exact at any lead."),
    ("moon_phase", "string", "—", "ASTRONOMICAL. Named phase."),
    ("sunrise_hour", "float", "local hour", "ASTRONOMICAL, from NOAA solar equations."),
    ("sunset_hour", "float", "local hour", "ASTRONOMICAL."),
    ("cpc_product", "string", "—", "Which CPC product supplied this row's nudge."),
    ("cpc_temp_cat", "string", "—", "Above / Below / Normal / EC tercile category at the proxy point."),
    ("cpc_temp_prob", "float", "%", "Tercile probability. 33 percent is Equal Chances and contributes no signal."),
    ("enso_expected_anom_f", "float", "°F", "ENSO_ANALOG. Zone-specific expected SST anomaly for the current regime, "
                                            "from the multi-decade ENSO composite."),
]

ESC_FIELDS = [
    ("date, zone_id, species_id", "string/date", "—", "Keys. One row per zone, species and extended date."),
    ("lead_days, confidence_tier, confidence_key", "int/string", "—", "Lead time and confidence tier."),
    ("score_outlook", "float", "0-100", "BLEND. Same species scoring engine as the 7-day tab, section 6 of "
                                        "build_dataset.py, executed unmodified against extended inputs."),
    ("score_lo / score_hi", "float", "0-100", "BLEND. Edges of the plausible score range: the model re-scored at "
                                              "sst_proj_lo_f and sst_proj_hi_f, widened ±3 pts (tier 2) or ±7 pts "
                                              "(tier 3), then ratcheted."),
    ("score_halfband_lo_pts / score_halfband_hi_pts", "float", "pts", "The ratcheted half-widths. Non-decreasing in "
                                                                      "lead by construction, before the 0-100 clip."),
    ("score_band_pts", "float", "pts", "Published band width, score_hi - score_lo."),
    ("score_band_raw_pts", "float", "pts", "AUDIT ONLY. Band width before the ratchet. Can narrow at long lead "
                                           "because the score response saturates near its soft ceiling."),
    ("score_band_is_ratcheted", "bool", "—", "True where the band was widened so it cannot imply rising certainty."),
    ("score_band_hits_ceiling / score_band_hits_floor", "bool", "—", "True where a band edge was clipped by the "
                                                                     "bounded 0-100 scale, so the drawn band is "
                                                                     "narrower than the modelled uncertainty."),
    ("climatological_score", "float", "0-100", "CLIMATOLOGY. The day-of-year seasonal norm score for this zone-species."),
    ("seasonal_norm_score", "float", "0-100", "CLIMATOLOGY. score_row(clim_mode=True), unchanged near-term methodology."),
    ("vs_seasonal_norm", "float", "pts", "score_outlook minus climatological_score."),
    ("trend", "string", "—", "THE PRIMARY TIER-3 OUTPUT. Qualitative label from vs_seasonal_norm: well above / above / "
                             "near / below / well below typical. Use this, not the daily number, past day 14."),
    ("fishability_outlook", "float", "0-100", "BLEND inside the model horizon, NULL for days 15-30 on purpose, "
                                              "because it depends on wind and swell."),
    ("term_sst, term_season, term_tide, term_moon, term_swell", "float", "0-1.35", "Individual driver responses. "
                                                                                   "term_swell is null where no wave "
                                                                                   "value exists."),
    ("anomaly_term", "float", "multiplier", "ENSO/anomaly multiplier applied to the weighted driver mean."),
    ("missing_drivers", "string", "—", "Comma-separated drivers dropped for this row. Weights renormalize over what "
                                       "remains; nothing is imputed."),
]


def md_table(rows):
    out = ["| Field | Type | Units | Definition |", "| --- | --- | --- | --- |"]
    out += [f"| `{f}` | {t} | {u} | {d} |" for f, t, u, d in rows]
    return "\n".join(out)


def splice(path, block):
    """Replace the marked block, or append it if absent. Never touches other content."""
    txt = open(path).read() if os.path.exists(path) else ""
    new = BEG + "\n" + block.strip() + "\n" + END
    if BEG in txt and END in txt:
        txt = txt[:txt.index(BEG)] + new + txt[txt.index(END) + len(END):]
    else:
        txt = txt.rstrip() + "\n\n" + new + "\n"
    open(path, "w").write(txt)
    print(f"  patched {os.path.relpath(path, ROOT)}")


def main():
    # ---------------------------------------------------------------- sources.json
    cfg = json.load(open(CFG))
    reg = [r for r in cfg["registry"] if r["id"] not in {s["id"] for s in NEW_SOURCES}]
    reg += NEW_SOURCES
    cfg["registry"] = reg
    gaps = [g for g in cfg["gaps"] if not g.startswith("Extended range")]
    cfg["gaps"] = gaps + NEW_GAPS
    json.dump(cfg, open(CFG, "w"), indent=1)
    print(f"  patched pipeline/config/sources.json ({len(reg)} sources, {len(cfg['gaps'])} gap notes)")

    # ---------------------------------------------------------------- source_registry.csv
    cols = ["name", "provider", "url", "endpoint", "used_for", "coverage", "cadence",
            "access", "units", "license", "limitations"]
    with open(os.path.join(CSV_DIR, "source_registry.csv"), "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in reg:
            w.writerow(r)
    print(f"  patched dataset/csv/source_registry.csv ({len(reg)} rows)")

    # ---------------------------------------------------------------- SOURCE_REGISTRY.md
    prov = os.path.join(CSV_DIR, "extended_field_provenance.csv")
    nprov = sum(1 for _ in open(prov)) - 1 if os.path.exists(prov) else 0
    blocks = ["## Extended-range (8-30 day) sources\n",
              "These feeds exist only to support the **30-Day Outlook** tab. The 1-7 day forecast does not use "
              "them and its methodology is unchanged.\n",
              "**Forecast vs historical pattern.** Every extended field is tagged with a `basis` in "
              f"[`dataset/csv/extended_field_provenance.csv`](../dataset/csv/extended_field_provenance.csv) "
              f"({nprov} fields). The taxonomy is:\n",
              "| `basis` | Meaning | Trust it? |",
              "| --- | --- | --- |",
              "| `forecast` | A real numerical or probabilistic forecast from a model run. | Yes, inside its stated horizon. |",
              "| `blend` | A forecast decayed toward the seasonal average as lead time grows. | Directionally, with its band. |",
              "| `enso_analog` | Expectation from historical years in a comparable ENSO state. | As a regime lean, not a date-specific value. |",
              "| `climatology` | A multi-decade seasonal average for this calendar window. **Not a forecast.** | As 'what is normal', yes. |",
              "| `astronomical` | Tide and lunar values from harmonic and orbital computation. | Yes, exactly, at any lead. |",
              "| `metadata` | A flag describing how another field was derived. | n/a |",
              ""]
    for s in NEW_SOURCES:
        blocks += [f"### {s['name']}\n",
                   f"- **Provider**: {s['provider']}",
                   f"- **Landing page**: {s['url']}",
                   f"- **Endpoint**: `{s['endpoint']}`",
                   f"- **Stations / points**: {s.get('stations', '—')}",
                   f"- **Used for**: {s['used_for']}",
                   f"- **Coverage retrieved**: {s['coverage']}",
                   f"- **Update cadence**: {s['cadence']}",
                   f"- **Access**: {s['access']}",
                   f"- **Units**: {s['units']}",
                   f"- **Licence**: {s['license']}",
                   f"- **Limitations**: {s['limitations']}",
                   ""]
    blocks += ["### Extended-range gaps and honest caveats\n"]
    blocks += [f"- {g}" for g in NEW_GAPS]
    blocks += ["", "### Considered and deliberately not used\n",
               "- **NWS SGX Coastal Waters Forecast** (`https://api.weather.gov/products/types/CWF/locations/SGX`) "
               "is a live, high-quality text product but reaches only about five days, entirely inside the "
               "existing near-term window, so it adds nothing at 8-30 days.",
               "- **Any 15-30 day daily wind or swell number.** Deterministic marine models have no useful skill "
               "at that lead. Publishing one would be the single most misleading thing this dashboard could do, "
               "so those fields are left null.",
               "- **CPC precipitation terciles** are fetched and stored for context but are not scored: rainfall "
               "has no direct term in the species model.", ""]
    splice(os.path.join(DOCS, "SOURCE_REGISTRY.md"), "\n".join(blocks))

    # ---------------------------------------------------------------- DATA_DICTIONARY.md
    dd = ["## `extended_outlook` (8-30 day)\n",
          "One row per zone and extended date. Each definition is prefixed with its basis so it is clear at a "
          "glance whether the number is a forecast or a historical pattern estimate.\n",
          md_table(EXT_FIELDS), "",
          "## `extended_scores` (8-30 day)\n",
          "One row per zone, species and extended date.\n",
          md_table(ESC_FIELDS), "",
          "## `forecast_confidence`\n",
          "The three confidence tiers, defined once in the pipeline and rendered verbatim in the UI so the "
          "dashboard cannot drift from the methodology: `tier`, `lead_from`, `lead_to`, `key`, `label`, `short`, "
          "`basis`, `shows`, `produced_by`.\n",
          "## Extended-range methodology notes\n",
          "- The extended tier reuses the **unmodified** scoring engine from section 6 of `build_dataset.py`, "
          "extracted at runtime and executed with injected dependencies. No scoring code is duplicated or "
          "reimplemented, so a change to the near-term model automatically changes the extended model too.",
          "- `w_persistence = exp(-(lead-6)/8)` and `w_enso_analog = 1 - w_persistence` are the only two shares "
          "and always sum to 1. The CPC outlook is applied as an **additive nudge**, not a third share, because "
          "treating it as a share made `w_persistence` jump back up at a tier boundary.",
          "- Drivers that do not exist at long lead (pressure, front, chlorophyll, and swell in the bays) are "
          "**dropped** and the remaining weights renormalize. Nothing is imputed. `missing_drivers` records "
          "exactly what was dropped per row.",
          "- Pressure is excluded from the extended score at **both** tiers, not just tier 3, specifically so "
          "the driver set does not change at the day 14/15 boundary.",
          "- The published score band never narrows as lead grows. See `score_band_is_ratcheted`.", ""]
    splice(os.path.join(DOCS, "DATA_DICTIONARY.md"), "\n".join(dd))

    # ---------------------------------------------------------------- README
    rd = ["## 30-Day Outlook\n",
          "The dashboard now carries a fourth view, **30-Day Outlook**, extending the horizon from 7 to 30 days "
          "in three explicitly labelled confidence tiers:\n",
          "| Tier | Lead | What it is | What it shows |",
          "| --- | --- | --- | --- |",
          "| High confidence | Days 1-7 | Observed conditions plus deterministic marine and atmospheric forecast. "
          "**Unchanged** by this addition. | Specific daily SST, swell, wind, tide and score |",
          "| Moderate confidence | Days 8-14 | Deterministic model decayed toward day-of-year climatology, plus the "
          "CPC 8-14 day outlook, plus exact tide and moon | Daily score with an uncertainty band; wind blended; "
          "swell only where the marine model still reaches |",
          "| Outlook / trend only | Days 15-30 | Climatology weighted with the ENSO analog composite, plus CPC "
          "week 3-4 and monthly outlooks, plus exact tide and moon | Trend versus the seasonal norm and a tide/moon "
          "quality signal. **No daily wind or swell numbers.** |",
          "",
          "Days 15-30 deliberately publish no daily wind or swell figures, because no public extended marine "
          "forecast has useful skill at that range. Field-by-field provenance is in "
          "`dataset/csv/extended_field_provenance.csv` and `docs/SOURCE_REGISTRY.md`.\n",
          "```bash",
          "python pipeline/fetch_extended.py      # CPC GIS outlooks, 40-day tides, 16-day models (slow, >10 min)",
          "python pipeline/build_extended.py     # extended tables, reusing the near-term scoring engine",
          "python pipeline/gen_extended_docs.py    # registry + dictionary (this script)",
          "python pipeline/append_extended_xlsx.py # add the extended sheets to the workbook",
          "python pipeline/stage_downloads.py      # populate app/downloads for the Data tab",
          "python pipeline/inject_extended.py    # additive patch of app/data.js",
          "```", ""]
    splice(os.path.join(ROOT, "README.md"), "\n".join(rd))


if __name__ == "__main__":
    print("patching registry and docs for the extended range:")
    main()
    print("done")
